jQuery(document).ready(function ($) {

    // Target the specific login form inside the modal
    // The modal login form ID generated by wp_login_form is usually #loginform
    var $modalLoginForm = $('#login-modal #loginform');
    var $statusDiv = $('<div class="login-status-message" style="margin-bottom:15px; padding:10px; border-radius:3px; display:none;"></div>');

    // Insert status message container before the login form starts
    $modalLoginForm.before($statusDiv);

    $modalLoginForm.on('submit', function (e) {
        e.preventDefault();

        var $form = $(this);
        var $button = $form.find('input[type="submit"]'); // wp_login_form uses input submit
        var originalBtnText = $button.val();

        // 1. Show Loading State
        $statusDiv.hide().removeClass('error success');
        $button.val('Signing in...').prop('disabled', true);

        // 2. Collect Data
        var data = {
            'action': 'omega_ajax_login',
            'username': $form.find('#user_login').val(),
            'password': $form.find('#user_pass').val(),
            'security': omega_ajax_login_obj.nonce
        };

        // 3. Send Request
        $.ajax({
            type: 'POST',
            dataType: 'json',
            url: omega_ajax_login_obj.ajaxurl,
            data: data,
            success: function (response) {
                if (response.loggedin == true) {
                    // SUCCESS
                    $statusDiv.addClass('success')
                        .text(response.message)
                        .css({ 'background-color': '#d4edda', 'color': '#155724', 'border': '1px solid #c3e6cb' })
                        .fadeIn();

                    // Redirect
                    window.location.href = response.redirect_url;
                } else {
                    // ERROR
                    $statusDiv.addClass('error')
                        .text(response.message)
                        .css({ 'background-color': '#f8d7da', 'color': '#721c24', 'border': '1px solid #f5c6cb' })
                        .fadeIn();

                    // Reset Button
                    $button.val(originalBtnText).prop('disabled', false);
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                // SYSTEM ERROR
                console.log(errorThrown);
                $statusDiv.addClass('error')
                    .text('System error. Please try again later.')
                    .css({ 'background-color': '#f8d7da', 'color': '#721c24', 'border': '1px solid #f5c6cb' })
                    .fadeIn();
                $button.val(originalBtnText).prop('disabled', false);
            }
        });
    });
});
